name: fpiv_graph
description: A comprehensive, high-performance graph algorithms library for Dart, built for speed and reliability in professional and educational projects.
version: 1.0.0
repository: https://github.com/FPIV/FPIV-Graph
homepage: https://fpiv.org
license: MIT

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
